#!/usr/bin/env python

import sys
import traceback
import logging
import bicleaner.util as util
#import bicleaner.features as features
import bicleaner.bicleaner_classifier_full as classifier


#import bicleaner

#from bicleaner import util, bicleaner_classifier_full


def main(argv):
	try:
        	util.logging_setup()
	        args = classifier.initialization() # Parsing parameters
	        classifier.main(args)  # Running main program
	except Exception as ex:
        	tb = traceback.format_exc()
	        logging.error(tb)
        	sys.exit(1)

if __name__=="__main__":
	main(sys.argv[1:])