#!/usr/bin/env python

import sys
import bicleaner

def main(argv):
	try:
        	bicleaner.util.logging_setup()
	        args = bicleaner.bicleaner-classifier-full.initialization() # Parsing parameters
	        bicleaner.bicleaner-classifier-full.main(args)  # Running main program
	except Exception as ex:
        	tb = traceback.format_exc()
	        bicleaner.util.logging.error(tb)
        	sys.exit(1)

if __name__=="__main__":
	main(sys.argv[1:])