#!/usr/bin/env python

import sys
import bicleaner.bicleaner_train_lite as train

def main(argv):
    args = train.initialization()
    train.main(args)

if __name__ == '__main__':
    main(sys.argv[1:])