#!/usr/bin/env python

import sys
import traceback
import logging
#import util
import bicleaner

#from bicleaner import util, bicleaner_classifier_full
from bicleaner import  * 

def main(argv):
	try:
        	bicleaner.util.logging_setup()
	        args = bicleaner.bicleaner_classifier_full.initialization() # Parsing parameters
	        bicleaner.bicleaner_classifier_full.main(args)  # Running main program
	except Exception as ex:
        	tb = traceback.format_exc()
	        logging.error(tb)
        	sys.exit(1)

if __name__=="__main__":
	main(sys.argv[1:])